### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by pkostaki**
Please, review wpf task 2.

**Description of structure of solution:**

- _StorageLib_ project represents classes to work with different types of storages (e.g. OneDrive, Google Drive, etc.). Intentionally seperate this project as it provides independed functionality and can be used by other net core application.
- _CustomControlLibrary_ project: represents actually control library with single control _OnlineStorageBrowser_.
- _WpfCloudExplorer_ - main project of wpf application that demo _OnlineStorageBrowser_ control.

**Description of Contol _OnlineStorageBrowser_** :
- properties exposes for customers:
  
  - fontsize, 
  - foreground,
  - iconsize,
  - template for treeview resource item view
- states implemented: 
  - not loaded state
  - loading state
  - loaded state
  - selected state
  - cut state

**Not implemented, but nice to have**:
	- have a block state while operation in progress 
	- sync resources functionality
	- show progress to those operations which support it.
	- think about using associate icons (OneDrive not provides it, Google Drive do)
	- cover all situation with unit tests
	- error handler make more specific as possible

	
**Details of implementation**:
- each online storage provider has list of operation that its supported e.g. google can copy file, but can't copy folder
	 onedrive able to copy both file and folder

### CODE REVIEW

**Comment by sassy224** [comment]
The exercise looks good, Konstantin! My only comment is about the separation of storage library and storage control. 
I think the storage library stand alone doesn't have much use, it's only useful when go together with storage control. Consider that if we release the WPF CloudExplorer component, I think it's better if customer only has to reference one assembly (Storage control which also include storage api), rather than references 2 assemblies (storage control and storage api).

Note that if we want to re-use storage api for other platforms, we have many choices:
- Share code (different projects share same files for storage api)
- Keep storage api in a netstandard project (similar to what you are doing)

What choice we choose will depend on many things, and it should be raised and discuss with Product Manager, Programming Manager.

**Comment by pkostaki** [comment]
> The exercise looks good, Konstantin! My only comment is about the separation of storage library and storage control.
> I think the storage library stand alone doesn't have much use, it's only useful when go together with storage control. Consider that if we release the WPF CloudExplorer component, I think it's better if customer only has to reference one assembly (Storage control which also include storage api), rather than references 2 assemblies (storage control and storage api).
> 
> Note that if we want to re-use storage api for other platforms, we have many choices:
> 
> * Share code (different projects share same files for storage api)
> * Keep storage api in a netstandard project (similar to what you are doing)
> 
> What choice we choose will depend on many things, and it should be raised and discuss with Product Manager, Programming Manager.

Undestood about shared code. More will learn from real code organized in c1 repos.

**Comment by IrinaPykhova** [comment]
I finally managed to look at code and application. Everything looks good to me. The only small thing - is bad sizing for png images. If there is any way to get something like svg, or multiple images of different sizes, then it worth trying. I see that google actually has images of different sizes: https://drive-thirdparty.googleusercontent.com/64/type/application/vnd.google-apps.folder

**Comment by pkostaki** [comment]
> I finally managed to look at code and application. Everything looks good to me. The only small thing - is bad sizing for png images. If there is any way to get something like svg, or multiple images of different sizes, then it worth trying. I see that google actually has images of different sizes: https://drive-thirdparty.googleusercontent.com/64/type/application/vnd.google-apps.folder

Yes, agree with you. I think that exercise has more things to do better in additional that you point. The question is about focus and goal of exercise. I mentioned about these things in a feedback from training by email.

**Pull request merged**
